/**
 * Lightweight chain-to-CoinGecko mapping for TokenLogo and other UI.
 * Avoids importing the heavy coingecko module in client components.
 */
export const CHAIN_TO_COINGECKO: Record<string, string> = {
  ethereum: "ethereum",
  polygon: "matic-network",
  "matic-network": "matic-network",
  matic: "matic-network",
  bnb: "binancecoin",
  arbitrum: "ethereum",
  optimism: "ethereum",
  avalanche: "avalanche-2",
  base: "ethereum",
  fantom: "fantom",
  cronos: "cronos",
  gnosis: "gnosis",
  zksync: "ethereum",
  linea: "ethereum",
  blast: "ethereum",
  mantle: "mantle",
  celo: "celo",
  moonbeam: "moonbeam",
  aurora: "ethereum",
  metis: "metis-token",
  scroll: "ethereum",
  mode: "ethereum",
  kava: "kava",
  harmony: "harmony",
  solana: "solana",
  bitcoin: "bitcoin",
  litecoin: "litecoin",
  dogecoin: "dogecoin",
  tether: "tether",
  "1": "ethereum",
  "56": "binancecoin",
  "137": "matic-network",
  "42161": "ethereum",
  "10": "ethereum",
  "43114": "avalanche-2",
  "8453": "ethereum",
  "250": "fantom",
  "25": "cronos",
  "100": "gnosis",
  "324": "ethereum",
  "59144": "ethereum",
  "81457": "ethereum",
  "5000": "mantle",
  "42220": "celo",
  "1284": "moonbeam",
  "1088": "metis-token",
  "534352": "ethereum",
  "34443": "ethereum",
  "2222": "kava",
  "1666600000": "harmony",
};
