/**
 * Static token image URLs from CoinGecko CDN.
 * Used for instant display without API calls. Falls back to API for unknown tokens.
 * Images sourced from CoinGecko - display with attribution per their API terms.
 */
export const COINGECKO_IMAGE_URLS: Record<string, string> = {
  bitcoin: "https://coin-images.coingecko.com/coins/images/1/small/bitcoin.png",
  ethereum: "https://coin-images.coingecko.com/coins/images/279/small/ethereum.png",
  tether: "https://coin-images.coingecko.com/coins/images/325/small/Tether.png",
  binancecoin: "https://coin-images.coingecko.com/coins/images/825/small/bnb-icon2_2x.png",
  solana: "https://coin-images.coingecko.com/coins/images/4128/small/solana.png",
  "usd-coin": "https://coin-images.coingecko.com/coins/images/6319/small/USDC.png",
  ripple: "https://coin-images.coingecko.com/coins/images/44/small/xrp-symbol-white-128.png",
  dogecoin: "https://coin-images.coingecko.com/coins/images/5/small/dogecoin.png",
  cardano: "https://coin-images.coingecko.com/coins/images/975/small/cardano.png",
  tron: "https://coin-images.coingecko.com/coins/images/1094/small/tron-logo.png",
  "avalanche-2": "https://coin-images.coingecko.com/coins/images/12559/small/Avalanche_Circle_RedWhite_Trans.png",
  chainlink: "https://coin-images.coingecko.com/coins/images/877/small/chainlink-new-logo.png",
  polkadot: "https://coin-images.coingecko.com/coins/images/12171/small/polkadot.png",
  "bitcoin-cash": "https://coin-images.coingecko.com/coins/images/780/small/bitcoin-cash-circle.png",
  polygon: "https://coin-images.coingecko.com/coins/images/4713/small/matic-token-icon.png",
  "shiba-inu": "https://coin-images.coingecko.com/coins/images/11939/small/shiba.png",
  litecoin: "https://coin-images.coingecko.com/coins/images/2/small/litecoin.png",
  dai: "https://coin-images.coingecko.com/coins/images/9956/small/Badge_Dai.png",
  uniswap: "https://coin-images.coingecko.com/coins/images/12504/small/uniswap.png",
  "wrapped-bitcoin": "https://coin-images.coingecko.com/coins/images/7598/small/wrapped_bitcoin_wbtc.png",
  stellar: "https://coin-images.coingecko.com/coins/images/100/small/Stellar_symbol_black_RGB.png",
  "true-usd": "https://coin-images.coingecko.com/coins/images/3449/small/tusd.png",
  "leo-token": "https://coin-images.coingecko.com/coins/images/8418/small/leo-token.png",
  cosmos: "https://coin-images.coingecko.com/coins/images/1481/small/cosmos_hub.png",
  "ethereum-classic": "https://coin-images.coingecko.com/coins/images/453/small/ethereum-classic-logo.png",
  aptos: "https://coin-images.coingecko.com/coins/images/26455/small/aptos_round.png",
  filecoin: "https://coin-images.coingecko.com/coins/images/12817/small/filecoin.png",
  "hedera-hashgraph": "https://coin-images.coingecko.com/coins/images/3688/small/hbar.png",
  arbitrum: "https://coin-images.coingecko.com/coins/images/16547/small/photo_2023-03-29_21.47.00.jpeg",
  "crypto-com-chain": "https://coin-images.coingecko.com/coins/images/7310/small/cro_token_logo.png",
  monero: "https://coin-images.coingecko.com/coins/images/69/small/monero_logo.png",
  optimism: "https://coin-images.coingecko.com/coins/images/25244/small/Optimism.png",
  "immutable-x": "https://coin-images.coingecko.com/coins/images/17233/small/immutableX.png",
  near: "https://coin-images.coingecko.com/coins/images/10365/small/near.jpg",
  "injective-protocol": "https://coin-images.coingecko.com/coins/images/12882/small/Secondary_Symbol.png",
  sui: "https://coin-images.coingecko.com/coins/images/26375/small/sui_asset.jpeg",
  maker: "https://coin-images.coingecko.com/coins/images/1364/small/Mark_Maker.png",
  "the-graph": "https://coin-images.coingecko.com/coins/images/13397/small/Graph_Token.png",
  "render-token": "https://coin-images.coingecko.com/coins/images/11645/small/rndr.png",
  bittensor: "https://coin-images.coingecko.com/coins/images/28452/small/ARUsPeNQ_400x400.jpeg",
  "fetch-ai": "https://coin-images.coingecko.com/coins/images/5681/small/Fetch.jpg",
  vechain: "https://coin-images.coingecko.com/coins/images/1167/small/VeChain-Logo-768x725.png",
  kaspa: "https://coin-images.coingecko.com/coins/images/25726/small/kaspa-icon-exchanges.png",
  "first-digital-usd": "https://coin-images.coingecko.com/coins/images/31079/small/fdusd.png",
  mantle: "https://coin-images.coingecko.com/coins/images/3334/small/mantle.jpg",
  "lido-dao": "https://coin-images.coingecko.com/coins/images/13573/small/Lido_DAO.png",
  celestia: "https://coin-images.coingecko.com/coins/images/31967/small/tia.jpg",
  "rocket-pool-eth": "https://coin-images.coingecko.com/coins/images/20764/small/reth.png",
  aave: "https://coin-images.coingecko.com/coins/images/12645/small/AAVE.png",
  algorand: "https://coin-images.coingecko.com/coins/images/4380/small/download.png",
  "matic-network": "https://coin-images.coingecko.com/coins/images/4713/small/matic-token-icon.png",
  fantom: "https://coin-images.coingecko.com/coins/images/4001/small/Fantom_round.png",
  cronos: "https://coin-images.coingecko.com/coins/images/7310/small/cro_token_logo.png",
  gnosis: "https://coin-images.coingecko.com/coins/images/662/small/logo_square_simple_300px.png",
  celo: "https://coin-images.coingecko.com/coins/images/11090/small/InjXBNx9_400x400.jpg",
  moonbeam: "https://coin-images.coingecko.com/coins/images/22459/small/glmr.png",
  "metis-token": "https://coin-images.coingecko.com/coins/images/15595/small/metis.png",
  kava: "https://coin-images.coingecko.com/coins/images/9761/small/kava.png",
  harmony: "https://coin-images.coingecko.com/coins/images/4344/small/Y88JAze.png",
};
